credentials:
  usernames:
    jsmith:
      email: jsmith@example.com
      name: John Smith
      password: 'ЗАШИФРОВАННЫЙ_ПАРОЛЬ_1'
    rdoe:
      email: rdoe@example.com
      name: Rebecca Doe
      password: 'ЗАШИФРОВАННЫЙ_ПАРОЛЬ_2'
cookie:
  expiry_days: 30
  key: 'some_random_key'
  name: 'some_cookie_name'
